### ISSUE TITLE
Error "Can not load file or assembly" Demos.WPF.CSharp.NetworkDiagramView.MainFeatures.dll "

### ISSUE THREAD

**Issue by it19862** [DlhSoftTeam/GanttChartLightLibrary-Demos#1]
At me at start there is an error.

_Unknown build error, "Unable to load file or assembly" file: /// C: \ test \ Project \ GanttChartLL \ Demos \ Samples \ WPF-CSharp \ NetworkDiagramView \ MainFeatures \ bin \ Debug \ Demos.WPF.CSharp.NetworkDiagramView. MainFeatures.dll "or one of their dependencies, it was expected that the module contains the assembly manifest."_

How to fix this error?

**Comment by DlhSoftTeam** [comment]
Hello! Please try right clicking the Samples folder and select Rebuild action there. That would build all individual samples and ensure the DLLs are available. Then just run the main Demos project.

Note, also, that if you just want to see the demos in action (and view part of the source code or download source code for individual samples as ZIPs) you can just run them from our Web site (we deployed this project as a ClickOnce app) here:
https://dlhsoft.com/GanttChartLightLibrary/Demos/Demos.application
